### ISSUE TITLE
缺少2个类文件

### ISSUE THREAD

**Issue by stoensin** [yangengzhe/webChat#1]
![image](https://cloud.githubusercontent.com/assets/8474954/24134017/6f8b07e8-0e3c-11e7-8908-d9d60e49e070.png)

**Comment by yangengzhe** [comment]
Global 是用来记录数据库信息的
security 是用来加密验证的。

与本系统无关系，处于安全考虑 我没有上传，你把这相关的操作删除 或修改下即可。不影响功能的使用
